const express = require('express')
const router = express.Router()
const {signup, login,loaduser,payment,order,loadorders,getusers,getorders,approve,cancle,complete,msg,getmsgs,Delete,upload,loadimgs,msgstatus,deleteimg,deleteorder,forgot,reset} = require("../Controllers/userController")
router.post('/signup',signup)
router.post('/login',login)
router.post('/loaduser',loaduser)
router.post('/payment',payment)
router.post('/order',order)
router.post('/loadorders',loadorders)
router.post('/approve',approve)
router.post('/cancle',cancle)
router.post('/complete',complete)
router.post('/msg',msg)
router.post('/delete',Delete)
router.post('/deleteorder',deleteorder)
router.post('/deleteimg',deleteimg)
router.post('/msgstatus',msgstatus)
router.post('/upload',upload)
router.post('/forgot',forgot)
router.post('/reset',reset)
router.get('/getusers',getusers)
router.get('/loadimgs',loadimgs)
router.get('/getmsgs',getmsgs)
router.get('/getorders',getorders)


module.exports = router